-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 26 avr. 2021 à 10:53
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `autocompletion`
--

-- --------------------------------------------------------

--
-- Structure de la table `informations`
--

DROP TABLE IF EXISTS `informations`;
CREATE TABLE IF NOT EXISTS `informations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(255) NOT NULL,
  `common_locations` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=82 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `informations`
--

INSERT INTO `informations` (`id`, `name`, `description`, `image`, `common_locations`) VALUES
(1, 'waterblight ganon', 'This phantom of Ganon attacked the Divine Beast Vah Ruta and was responsible for the demise of the Champion Mipha. It attacks with a spear and ice magic.', 'https://botw-compendium.herokuapp.com/api/v2/entry/waterblight_ganon/image', 'Divine Beast Vah Ruta'),
(2, 'rock octorok', 'This octopus-like species of monster lives in volcanic regions. When they inhale, they\'re preparing to spit out flaming rocks but have been known to suck up weapons or bombs in the same breath.', 'https://botw-compendium.herokuapp.com/api/v2/entry/rock_octorok/image', 'Eldin Canyon'),
(3, 'moblin', 'This heavyweight species of monster can be found all over Hyrule. They\'re physically very strong, their legs along strong enough to resist the force of a bomb blast. They\'re much more dangerous than the Bokoblins. In fact, Moblins have been known to pick up Bokoblins and throw them as makeshift projectile weapons.', 'https://botw-compendium.herokuapp.com/api/v2/entry/moblin/image', 'Hyrule Field'),
(4, 'silver lynel', 'Silver Lynels are not to be trifled with. They have been influenced by Ganon\'s fiendish magic, so they are the strongest among the Lynel species, surpassing even the strength of those with white manes. The term \"silver\" denotes not only their color but also their rarity. The purple stripes help them to stand out even more.', 'https://botw-compendium.herokuapp.com/api/v2/entry/silver_lynel/image', 'Undefined'),
(5, 'silver lizalfos', 'These Lizalfos have been influenced by Ganon\'s fiendish magic to become the strongest Lizalfos of all. They\'re called \"silver\" for their unique coloring and also to denote their rarity. Their purple pattern makes them even more distinct.', 'https://botw-compendium.herokuapp.com/api/v2/entry/silver_lizalfos/image', 'Undefined'),
(6, 'thunder wizzrobe', 'These spell-casting monsters can be found all over Hyrule. They use their thunderstorm rods to hurl balls of electricity or to summon monsters surging with electricity and have been known to cause thunderstorms in the area. The weather will normalize once the Wizzrobe is defeated.', 'https://botw-compendium.herokuapp.com/api/v2/entry/thunder_wizzrobe/image', 'Hyrule Field'),
(7, 'blue moblin', 'These heavyweight monsters can be found all over Hyrule. They\'re much tougher than their standard counterparts and often have much stronger weapons equipped.', 'https://botw-compendium.herokuapp.com/api/v2/entry/blue_moblin/image', 'Hyrule Field'),
(8, 'black moblin', 'These heavyweight monsters can be found all over Hyrule and are among the most dangerous types of Moblin. They\'re extremely resilient and are often armed with some of the strongest weapons Moblins can carry.', 'https://botw-compendium.herokuapp.com/api/v2/entry/black_moblin/image', 'Hyrule Field'),
(9, 'cursed bokoblin', 'The Malice has given these Bokoblin skulls a sort of life. Devoid of any intelligence the Bokoblin it once belonged to may have had, these pitiful things now exist only to attack anything that gets too close.', 'https://botw-compendium.herokuapp.com/api/v2/entry/cursed_bokoblin/image', 'Undefined'),
(10, 'hinox', 'The largest monster to make its home in Hyrule, the Hinox lives primarily in forested areas. A keen awareness of your surroundings is paramount when facing one, as Hinox are known for tearing entire trees from the ground and using them as weapons. A deft hand can steal weapons off the necklaces they wear.', 'https://botw-compendium.herokuapp.com/api/v2/entry/hinox/image', 'East Necluda'),
(11, 'stone talus (luminous)', 'This enormous monster is naturally camouflaged as a rock formation. Neither sword nor arrow can pierce its stony form, but a cunning adventurer knows to scale its body and attack the ore sprouting from its peak. Unlike your average Stone Talus, this type\'s ore deposit consists mostly of luminous stone.', 'https://botw-compendium.herokuapp.com/api/v2/entry/stone_talus_(luminous)/image', 'Gerudo Highlands'),
(12, 'igneo talus titan', 'This monster is an Igneo Talus subspecies that is camouflaged as molten rock. It lives in lava for many years before emerging at an enormous size. It is wildly powerful and emits a tremendous amount of heat, causing a constant updraft in its vicinity. This monster is so fearsome it has earned the title of Titan.', 'https://botw-compendium.herokuapp.com/api/v2/entry/igneo_talus_titan/image', 'Undefined'),
(13, 'meteo wizzrobe', 'These spell-casting monsters can be found all over Hyrule. They use their meteor rods to hurl fireballs or to summon flaming monsters and have been known to severely raise the temperature around them. The weather will normalize once the Wizzrobe is defeated.', 'https://botw-compendium.herokuapp.com/api/v2/entry/meteo_wizzrobe/image', 'Hyrule Field'),
(14, 'stalmoblin', 'The remains of Moblins appear in the dark of the night. Even the toughest Moblins become fragile when they\'re little more than a pile of bones, so they\'ll crumble after just a few attacks. However, as long as a skull remains intact, they\'ll continue to pull themselves back together and go on fighting.', 'https://botw-compendium.herokuapp.com/api/v2/entry/stalmoblin/image', 'Great Hyrule Forest'),
(15, 'ice chuchu', 'This low-level gel monster is engulfed in freezing-cold air. Its strength varies depending on its size. It tends to explode if attacked from close range, so the use of spears, arrows, and other ranged weapons is advised.', 'https://botw-compendium.herokuapp.com/api/v2/entry/ice_chuchu/image', 'Gerudo Highlands'),
(16, 'thunderblight ganon', 'This phantom of Ganon attacked the Divine Beast Vah Naboris and was responsible for the demise of the Champion Urbosa. It specializes in quick, lightning-based attacks.', 'https://botw-compendium.herokuapp.com/api/v2/entry/thunderblight_ganon/image', 'Divine Beast Vah Naboris'),
(17, 'cursed moblin', 'The Malice has given these Moblin skulls a pitiful life after death. The only fragment of their former selves they\'ve held on to is the ferocity innate to all Moblins, so they will attack anyone that approaches.', 'https://botw-compendium.herokuapp.com/api/v2/entry/cursed_moblin/image', 'Undefined'),
(18, 'fire wizzrobe', 'These spell-casting monsters can be found all over Hyrule. They use their fire rods to hurl fireballs or to summon flaming monsters and have been known to severely raise the temperature around them. The weather will normalize once the Wizzrobe is defeated.', 'https://botw-compendium.herokuapp.com/api/v2/entry/fire_wizzrobe/image', 'Hyrule Field'),
(19, 'guardian scout iii', 'Although originally designed by an ancient civilisation to combat Ganon, these scaled-down Guardians were placed inside shrines as part or the trials. This model is equipped with twin-blade functionality to further test the combat prowess of one undertaking the trials. It takes a nimble fighter to overcome this one.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_scout_iii/image', 'Undefined'),
(20, 'molduking', 'This massive monster swims beneath the desert\'s sand. It is a subspecies of Molduga that stored up a great deal of energy by sleeping underground for hundreds of years. Its power is superior to Molduga, as its skin is rich with iron and acts as a protective shield.', 'https://botw-compendium.herokuapp.com/api/v2/entry/molduking/image', 'Undefined'),
(21, 'electric wizzrobe', 'These spell-casting monsters can be found all over Hyrule. They use their lightning rods to hurl balls of electricity or to summon monsters surging with electricity and have been known to cause thunderstorms in the area. The weather will normalize once the Wizzrobe has been defeated.', 'https://botw-compendium.herokuapp.com/api/v2/entry/electric_wizzrobe/image', 'Hyrule Ridge'),
(22, 'molduga', 'This massive monster swims beneath the desert\'s sand. It spends most of its time submerged, but if it senses sound, it will breach the surface to feast on whatever it can grab. Running around carelessly can be dangerous if you suspect there may be one in the area.', 'https://botw-compendium.herokuapp.com/api/v2/entry/molduga/image', 'Gerudo Desert'),
(23, 'black lizalfos', 'These quick-witted, lizard-like monsters can be found all over Hyrule. This particular type tends to carry some pretty strong weapons, so they are among the most dangerous Lizalfos.', 'https://botw-compendium.herokuapp.com/api/v2/entry/black_lizalfos/image', 'Hyrule Field'),
(24, 'igneo pebblit', 'A very young Igneo Talus. Their bodies toughen as they mature and convert fully into lava by adulthood. As a child, however, while still covered in fire, their bodies are fragile and light enough to be blown away by a bomb\'s blast.', 'https://botw-compendium.herokuapp.com/api/v2/entry/igneo_pebblit/image', 'Eldin Canyon'),
(25, 'farosh', 'A spirit of lightning has taken the form of this giant dragon. Making its home in the Faron region, it\'s said to have served the Spring of Courage since ancient times. An old saying goes, \"The dragon ascends to the heavens as the sun begins to set,\" but nobody has seen this in the current age. The electricity that coats its body makes it dangerous to get near, but Farosh bears no ill will toward people.', 'https://botw-compendium.herokuapp.com/api/v2/entry/farosh/image', 'Lake Hylia'),
(26, 'electric chuchu', 'This low-level gel monster is engulfed in electricity. Its strength varies depending on its size. It tends to explode if attacked from close range, so the use of spears, arrows, and other ranged weapons is advised.', 'https://botw-compendium.herokuapp.com/api/v2/entry/electric_chuchu/image', 'Gerudo Highlands'),
(27, 'dinraal', 'A spirit of fire has taken the form of this giant dragon. Making its home in the Eldin region, it\'s said to have served the Spring of Power since ancient times. An old saying goes, \"The dragon ascends to the heavens as the sun begins to set,\" but nobody has witnessed this in the current age. The flames that coat its body make it dangerous to get near, but Dinraal bears no ill will toward people.', 'https://botw-compendium.herokuapp.com/api/v2/entry/dinraal/image', 'Eldin Mountains'),
(28, 'blue-maned lynel', 'These fearsome monsters have lived in Hyrule since ancient times. Compared to the standard Lynel, those with blue manes much tougher and equipped with much stronger weapons. Facing off against a Lynel is ill-advised, but if you must, be sure you\'re well prepared.', 'https://botw-compendium.herokuapp.com/api/v2/entry/blue-maned_lynel/image', 'Hyrule Field'),
(29, 'guardian turret', 'The Sheikah of ancient Hyrule developed this as a weapon to combat Ganon. This stationary model was used for defending important structures. Its offensive power is on par with other Guardians, and omitting the legs kept the manufacturing costs low.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_turret/image', 'Hyrule Castle'),
(30, 'master kohga', 'The leader of the Yiga Clan, a group formed with just a single objective: eliminate Link. He sends his minions all over Hyrule in search of you but tends to spend most of his time napping and generally loafing about. Despite this, his mastery of the esoteric arts has earned him a deep respect. Even if he were to die, his followers would never give up on their one and only task.', 'https://botw-compendium.herokuapp.com/api/v2/entry/master_kohga/image', 'Yiga Clan Hideout'),
(31, 'cursed lizalfos', 'The Malice has given these Lizalfos skulls a sorry form of life after death. Only the slyness of their former selves remains, making them faster than Bokoblin skulls. They thoughtlessly attack anyone who approaches.', 'https://botw-compendium.herokuapp.com/api/v2/entry/cursed_lizalfos/image', 'Undefined'),
(32, 'yiga blademaster', 'These are the elite soldiers of the Yiga Clan. They favor the windcleaver blade and are extremely agile despite their bulky build. At this Yiga Clan rank, they have mastered a technique that allows them to manipulate the very earth. By striking the ground, they can create stone pillars and blasts of air.', 'https://botw-compendium.herokuapp.com/api/v2/entry/yiga_blademaster/image', 'Undefined'),
(33, 'guardian scout ii', 'Although originally designed by an ancient civilization to combat Ganon, these scaled-down Guardians were placed inside shrines as part of the trials. In additional to the beam functionality, this particular model was designed to handle weaponry as a means of further testing the combat prowess of one undertaking the trials. It takes some serious skill to go toe-to-toe with one of these.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_scout_ii/image', 'Undefined'),
(34, 'windblight ganon', 'This phantom of Ganon attacked the Divine Beast Vah Medoh and was responsible for the demise of the Champion Revali. It specializes in long-ranged wind attacks.', 'https://botw-compendium.herokuapp.com/api/v2/entry/windblight_ganon/image', 'Divine Beast Vah Medoh'),
(35, 'frost pebblit', 'A very young Frost Talus. Their bodies toughen and frost over as they mature, becoming entirely made of ice by adulthood. As a child, however, their bodies are awfully fragile and are light enough to be blown away by a bomb\'s blast.', 'https://botw-compendium.herokuapp.com/api/v2/entry/frost_pebblit/image', 'Hebra Mountains'),
(36, 'ice-breath lizalfos', 'These quick-witted, lizard-like monsters can be found all over Hyrule. The balls of ice they spit make them particularly troublesome, but exposure to fire will kill them instantly. Their homes are mainly on snowy mountains.', 'https://botw-compendium.herokuapp.com/api/v2/entry/ice-breath_lizalfos/image', 'Gerudo Highlands'),
(37, 'black hinox', 'The largest monster to make its home in Hyrule, the Hinox lives primarily in forested areas. A keen awareness of your surroundings is paramount when facing one, as Hinox are known for tearing entire trees from the ground and using them as weapons. Black Hinox wear metal greaves that conduct electricity rather well. A deft hand can steal weapons off the necklaces they wear.', 'https://botw-compendium.herokuapp.com/api/v2/entry/black_hinox/image', 'East Necluda'),
(38, 'lynel', 'These fearsome monsters have lived in Hyrule since ancient times. They possess intense intelligence, resilience, and strength, making them among the most dangerous monsters in all the land. This is compounded by the fact that they have a natural resistance to all elements. You would be wise to challenge a Lynel only if you\'re very well prepared.', 'https://botw-compendium.herokuapp.com/api/v2/entry/lynel/image', 'Lanayru Great Spring'),
(39, 'keese', 'The unpredictable flight pattern of this noctoural bat-like species can make fighting them a nuisance, but they\'re weak enough to fell with a single strike. Sometimes they\'ll attack in packs, but even then, a pack can be sent packing with a single attack.', 'https://botw-compendium.herokuapp.com/api/v2/entry/keese/image', 'Hyrule Field'),
(40, 'ice wizzrobe', 'These spell-casting monsters can be found all over Hyrule. They use their ice rods to create freezing blasts of air or to summon frozen monsters and have been known to cause blizzards to severely decrease the temperatures around them. The weather will normalize once the Wizzrobe is defeated.', 'https://botw-compendium.herokuapp.com/api/v2/entry/ice_wizzrobe/image', 'Gerudo Highlands'),
(41, 'frost talus', 'This enormous monster is naturally camouflaged as a frozen rock formation. Neither sword nor arrow can pierce its frigid form. Merely touching its frosty body can leave you with severe frostbite, but you may be able to scale it if you use something to thaw its icy exterior.', 'https://botw-compendium.herokuapp.com/api/v2/entry/frost_talus/image', 'Hebra Mountains'),
(42, 'stalkoblin', 'The remains of Bokoblins appear in the dark of the night. While they\'re fragile enough to crumble from a single blow, as long as a skull remains intact, they\'ll continue to pull themselves back together and go on fighting. Sometimes the body will pick up the wrong skull, but this doesn\'t seem to be a problem...', 'https://botw-compendium.herokuapp.com/api/v2/entry/stalkoblin/image', 'Hyrule Field'),
(43, 'guardian skywatcher', 'The Sheikah of ancient Hyrule developed this as a weapon to combat Ganon. This flying model is an improvement over the walking type, capable of either attacking or surveying from the air. Destroying the propeller will ground it.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_skywatcher/image', 'Hyrule Field'),
(44, 'blue hinox', 'The largest monster to make its home in Hyrule, the Hinox lives primarily in forested areas. A keen awareness of your surroundings is paramount when facing one, as Hinox are known for tearing entire trees from the ground and using them as weapons. Blue Hinox wear greaves that can be burnt away to expose their feet. A deft hand can steal weapons off the necklaces they wear.', 'https://botw-compendium.herokuapp.com/api/v2/entry/blue_hinox/image', 'Hyrule Field'),
(45, 'stone pebblit', 'A very young Stone Talus. Their bodies toughen as they mature, becoming as tough as boulders by adulthood. As a child, however, their bodies are light enough to be lifted and fragile enough to break when thrown.', 'https://botw-compendium.herokuapp.com/api/v2/entry/stone_pebblit/image', 'Greater Hyrule'),
(46, 'stalizalfos', 'The remains of Lizalfos appear in the dark of night. They\'re as sly as ever, even now that they\'re just some bones stacked atop each other. However, their bodies are much more fragile, and a single solid hit can reduce them to pieces. If a skull remains intact, they will pull themselves back up and continue to fight. They\'ve been known to grab the wrong skull at times, but they never seem to mind...', 'https://botw-compendium.herokuapp.com/api/v2/entry/stalizalfos/image', 'Gerudo Desert'),
(47, 'silver bokoblin', 'You would be foolish to call these Silver Bokoblins a mere nuisance. They have been influenced by Ganon\'s fiendish magic, so they are stronger than even the Black Bokoblins. They\'re called \"silver\" not only because of their coloring but also to denote their rarity. The purple markings help them to stand out even more.', 'https://botw-compendium.herokuapp.com/api/v2/entry/silver_bokoblin/image', 'Undefined'),
(48, 'guardian stalker', 'The Sheikah of ancient Hyrule developed this as a weapon to combat Ganon. Its six legs give it extraordinary mobility compared to most current vehicles, and its powerful laser provides far greater offensive capability than conventional weaponry. Destroying the legs severely reduces its mobility.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_stalker/image', 'Hyrule Field'),
(49, 'forest octorok', 'Although originally an aquatic species, this type has adapted to life in the forest. They hide among the trees, disguising themselves as grass or unassuming shrubbery, and then attack when someone wanders by.', 'https://botw-compendium.herokuapp.com/api/v2/entry/forest_octorok/image', 'Hyrule Ridge'),
(50, 'fire chuchu', 'This low-level gel monster is engulfed in flames. Its strength varies depending on its size. It tends to explode if attacked from close range, so the use of spears, arrows, and other ranged weapons is advised.', 'https://botw-compendium.herokuapp.com/api/v2/entry/fire_chuchu/image', 'Eldin Canyon'),
(51, 'fireblight ganon', 'This phantom of Ganon attacked the Divine Beast Vah Rudania and was responsible for the demise of the Champion Daruk. It attacks with a greatsword and fire magic.', 'https://botw-compendium.herokuapp.com/api/v2/entry/fireblight_ganon/image', 'Divine Beast Vah Rudania'),
(52, 'igneo talus', 'This enormous monster is naturally camouflaged as molten rock. Neither sword nor arrow can pierce its fiery form. Merely touching its magma-hot body can burn you pretty badly, but you may be able to scale it if you can use something to chill its flames.', 'https://botw-compendium.herokuapp.com/api/v2/entry/igneo_talus/image', 'Eldin Canyon'),
(53, 'snow octorok', 'These octopus-like monsters live in snowy fields and disguise themselves as grass. When someone wanders by, they spring into action and attack by spitting snowballs.', 'https://botw-compendium.herokuapp.com/api/v2/entry/snow_octorok/image', 'Gerudo Highlands'),
(54, 'dark beast ganon', 'After Ganon was defeated by Link, the remaining Malice pulled itself together to form this bestial creature. Its appearance and fiendish magic eared it the name of Dark Beast. This form is considered to be Ganon\'s original, although in this state, his awareness has been consumed entirely by Malice, and all he knows is a desire to rampage and destroy.', 'https://botw-compendium.herokuapp.com/api/v2/entry/dark_beast_ganon/image', 'Hyrule Field'),
(55, 'chuchu', 'This low-level, gel-based monster can be found all over Hyrule. It tends to spring its attacks on unsuspecting prey from the ground or from trees. Its strength varies by size, and the type of jelly it drops varies depending on whether the Chuchu was heated up, cooled down, or shocked.', 'https://botw-compendium.herokuapp.com/api/v2/entry/chuchu/image', 'Hyrule Field'),
(56, 'blue bokoblin', 'This common species is a nuisance all over Hyrule. They\'re tougher and have stronger weapons than the red Bokoblins - and are a little more clever, as well. At the very least, they have figured out that they can simply kick a Remote Bomb out of the way to avoid its blast.', 'https://botw-compendium.herokuapp.com/api/v2/entry/blue_bokoblin/image', 'Gerudo Desert'),
(57, 'guardian scout iv', 'An ancient civilization originally designed Guardians to combat Ganon but then scaled them down to place in shrines as part of the trials. This model is very resilient and has been outfitted with triple-blade functionality, allowing it to wield three weapons. This will put any would-be hero to the test for sure. A great deal of strength and confidence alike are required to contend with one of these.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_scout_iv/image', 'Undefined'),
(58, 'stone talus (rare)', 'This enormous monster is naturally camouflaged as a rock formation. Neither stone nor arrow can pierce its stony form, but a cunning adventurer knows to scale its body and attack the ore sprouting from its peak. Unlike your average Stone Talus, this type\'s ore deposit contains a large amount of precious ore.', 'https://botw-compendium.herokuapp.com/api/v2/entry/stone_talus_(rare)/image', 'Hyrule Field'),
(59, 'stalnox', 'The mere remains of what was once a giant monster known as a Hinox. These skeletal beasts appear at nighttime. Much like their living counterparts, the Stalnox will tear entire trees from the ground to use as weapons. Furthermore, even if it appears defeated at first, it will keep coming back for more as long as its eye is left intact.', 'https://botw-compendium.herokuapp.com/api/v2/entry/stalnox/image', 'Hyrule Field'),
(60, 'stone talus', 'This enormous monster is naturally camouflaged as a rock formation. Neither sword nor arrow can pierce its stony form, but a cunning adventurer knows to scale its body and attack the ore sprouting from its peak.', 'https://botw-compendium.herokuapp.com/api/v2/entry/stone_talus/image', 'West Necluda'),
(61, 'calamity ganon', 'The source of the darkness that has appeared time and again throughout Hyrule\'s history. It\'s been called many names, from \"Great King of Evil\" to \"Calamity.\" Hibernating within a cocoon, it attempted to regenerate a physical form after Link awoke but was forced to confront him in an incomplete state.', 'https://botw-compendium.herokuapp.com/api/v2/entry/calamity_ganon/image', 'Hyrule Castle'),
(62, 'guardian scout i', 'Guardians were originally designed by an ancient civilization to combat Ganon, but these smaller models were placed inside shrines as part of the trials found within. The multiple legs and beam functionality were scaled down but kept mostly intact.', 'https://botw-compendium.herokuapp.com/api/v2/entry/guardian_scout_i/image', 'Undefined'),
(63, 'treasure octorok', 'These particularly clever monsters bury themselves in deep sand or snow and disguise themselves as treasure chests. Anyone who approaches the chests is attacked. The treasures chests are not magnetic, which proves that they are actually a part of these monsters\' bodies.', 'https://botw-compendium.herokuapp.com/api/v2/entry/treasure_octorok/image', 'Gerudo Highlands'),
(64, 'ice keese', 'The intense frost that engulfs the bodies of these bat-like Keese makes them more dangerous than the standard type. They\'re capable of freezing anything they touch.', 'https://botw-compendium.herokuapp.com/api/v2/entry/ice_keese/image', 'Hebra Mountains'),
(65, 'naydra', 'A spirit of ice has taken the form of this giant dragon. Making its home in the Lanayru region, it\'s said to have served the Spring of Wisdom since ancient times. An old saying goes, \"The dragon ascends to the heavens as the sun begins to set,\" but nobody has seen this in the current age. The ice that coats its body makes it dangerous to get near, but Naydra bears no ill will toward people.', 'https://botw-compendium.herokuapp.com/api/v2/entry/naydra/image', 'Mount Lanayru'),
(66, 'fire-breath lizalfos', 'These quick-witted, lizard-like monsters can be found all over Hyrule. Their fiery breath makes them pretty dangerous, but exposure to cold will kill them instantly. They mainly make their homes in volcanic areas but have also been sighed in the Akkala region.', 'https://botw-compendium.herokuapp.com/api/v2/entry/fire-breath_lizalfos/image', 'Eldin Canyon'),
(67, 'blizzrobe', 'These spell-casting monsters can be found all over Hyrule. They use their blizzard rods to create freezing blasts of air or to summon frozen monsters and have been known to cause blizzards to severely decrease the temperature around them. The weather will normalize once the Blizzrobe is defeated.', 'https://botw-compendium.herokuapp.com/api/v2/entry/blizzrobe/image', 'Hyrule Field'),
(68, 'sentry', 'These sentries dispatched from Divine Beast Vah Rudania are equipped with searchlights that can spot intruders.', 'https://botw-compendium.herokuapp.com/api/v2/entry/sentry/image', 'Death Mountain'),
(69, 'electric lizalfos', 'These quick-witted, lizard-like monsters can be found all over Hyrule. The can emit strong electrical currents from their bodies, so don\'t get too close. Their horns are brimming with electricity, which will discharge and arc to nearby areas if struck by an arrow. They tend to live in desert climates.', 'https://botw-compendium.herokuapp.com/api/v2/entry/electric_lizalfos/image', 'Gerudo Desert'),
(70, 'bokoblin', 'This common species is a nuisance all over Hyrule. Some have unified in the time following the Great Calamity and have formed factions of bandits. While not very clever, they are at least intelligent enough to hunt beasts and grill their meat for food. Though they\'re typically ferocious carnivores, they actually enjoy fruit as well.', 'https://botw-compendium.herokuapp.com/api/v2/entry/bokoblin/image', 'Hyrule Field'),
(71, 'silver moblin', 'The strongest of all Moblins, Ganon\'s fiendish magic has allowed them to surpass even the Black Moblins in strength and resilience. They\'re called \"silver\" for both their body color as well as their rarity. The purple patterns on their bodies also help them to stand out.', 'https://botw-compendium.herokuapp.com/api/v2/entry/silver_moblin/image', 'Undefined'),
(72, 'monk maz koshia', 'The arbiter of worthiness for the hero who wishes to control a Divine Beast, following a revelation from the Goddess Hylia. As the last part of the final trial, the monk offers a challenge of ancient techniques.', 'https://botw-compendium.herokuapp.com/api/v2/entry/monk_maz_koshia/image', 'Undefined'),
(73, 'lizalfos', 'These quick-witted, lizard-like monsters can be found all over Hyrule. They\'re a sly species that lurks underwater or uses camouflage to blend in with the environment to launch ambushes. Moreover, they never sleep. They\'re meat eaters by nature but will enjoy the occasional insect or two.', 'https://botw-compendium.herokuapp.com/api/v2/entry/lizalfos/image', 'Lanayru Great Spring'),
(74, 'water octorok', 'Although they spend most of their time in water, the drop in barometric pressure that occurs when it rains causes an air sac within these octopus-like monsters to inflate and lift them into the air. The rocks they spit out can be bounced back with a shield.', 'https://botw-compendium.herokuapp.com/api/v2/entry/water_octorok/image', 'West Necluda'),
(75, 'decayed guardian', 'The Sheikah of ancient Hyrule developed this as a weapon to combat Ganon, but it was destroyed during the Great Calamity. Ages of weather and neglect have left it in a state of disrepair. Approach with caution; some of the derelict models have been known to awaken from stasis and attack when approached.', 'https://botw-compendium.herokuapp.com/api/v2/entry/decayed_guardian/image', 'Hyrule Field'),
(76, 'electric keese', 'The electricity that engulfs the bodies of these bat-like Keese makes them more dangerous than the standard type. They\'re capable of shocking anything they touch.', 'https://botw-compendium.herokuapp.com/api/v2/entry/electric_keese/image', 'Lanayru Great Spring'),
(77, 'black bokoblin', 'Although Bokoblins are generally a nuisance, the Black Bokoblins are among the most dangerous type. They\'re extremely resilient, and many are armed with more advanced weapons.', 'https://botw-compendium.herokuapp.com/api/v2/entry/black_bokoblin/image', 'Hyrule Field'),
(78, 'white-maned lynel', 'These fearsome monsters have lived in Hyrule since ancient times. Their ability to breathe fire makes White-Maned Lynels among the toughest of the species; each one of their attacks is an invitation to the grave. There are so few eyewitness accounts of this breed because a White-Maned Lynel is not one to let even simple passersby escape with their lives.', 'https://botw-compendium.herokuapp.com/api/v2/entry/white-maned_lynel/image', 'Hyrule Field'),
(79, 'blue lizalfos', 'These quick-witted, lizard-like monsters can be found all over Hyrule. Compared to the green Lizalfos, many of these carry much stronger weapons and are generally much tougher.', 'https://botw-compendium.herokuapp.com/api/v2/entry/blue_lizalfos/image', 'Tabantha Frontier'),
(80, 'fire keese', 'The fire that engulfs the bodies of these bat-like Keese makes them more dangerous than the standard type. They\'re capable of setting fire to anything they touch.', 'https://botw-compendium.herokuapp.com/api/v2/entry/fire_keese/image', 'Eldin Canyon'),
(81, 'yiga footsoldier', 'The lowest-ranked members of the Yiga Clan. They\'ve been dispatched all across Hyrule with a single task: seek out Link and end his life. They\'re a crafty bunch, sometimes disguising themselves as simple travelers or villagers to get the jump on you. Be wary of suspicious people you encounter. They\'re very agile and carry a bow and one-handed sword.', 'https://botw-compendium.herokuapp.com/api/v2/entry/yiga_footsoldier/image', 'Undefined');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
